version: 2
updates:
  - package-ecosystem: github-actions
    directory: docker-compose-deploy
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"

  - package-ecosystem: github-actions
    directory: server-certificate
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"
