name: Docker Compose Deploy
description: Deploy to the remote server using docker-compose
inputs:
  COMPOSE_FILE_PATH:
    description: The path to the compose file to use for deployment
    required: true
    default: docker-compose.yaml
  DOCKER_CERT_PATH:
    description: DOCKER_CERT_PATH
    required: true
    default: certs
  STACK_NAME:
    description: Name of the stack to create
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "ARGS=-f ${{ inputs.COMPOSE_FILE_PATH }} -p ${{ inputs.STACK_NAME }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "DOCKER_CERT_PATH=${{ inputs.DOCKER_CERT_PATH }}" >> $GITHUB_ENV
      shell: bash
    - run: docker-compose ${{ env.ARGS }} build --pull
      shell: bash
    - run: docker-compose ${{ env.ARGS }} pull
      shell: bash
    - run: docker-compose ${{ env.ARGS }} up -d --remove-orphans
      shell: bash
    - run: docker network connect ${{ inputs.STACK_NAME }} nginx-proxy || true
      shell: bash
